language: c
install:
  - sudo apt-get update
  - sudo apt-get install -y rubygems
  - gem install mustache -v 0.7.0
  - gem install ronn
  - autoreconf -i
script:
  - ./configure && make && make check
